Sys.Extended.UI.Localization["zh-CHT"] = {
    "AlwaysVisible_ElementRequired": "必須替 Sys.Extended.UI.AlwaysVisibleControlBehavior 指定一個項目",
    "Animation_CannotNestSequence": "Sys.Extended.UI.Animation.ParallelAnimation 不能內含 Sys.Extended.UI.Animation.SequenceAnimation",
    "Animation_ChildrenNotAllowed": "Sys.Extended.UI.Animation.createAnimation 無法加入一個不是衍生自 Sys.Extended.UI.Animation.ParentAnimation 且類型為 {0} 的子動畫",
    "Animation_InvalidBaseType": "Sys.Extended.UI.Animation.registerAnimation 只能註冊那些繼承自 Sys.Extended.UI.Animation.Animation 的類型",
    "Animation_InvalidColor": "標記名稱 Color 必須是 7 個字元的 16 進位字串（例如：#246ACF），不能是 {0}",
    "Animation_MissingAnimationName": "Sys.Extended.UI.Animation.createAnimation 必須持有一個 AnimationName 屬性的物件",
    "Animation_NoDynamicPropertyFound": "Sys.Extended.UI.Animation.createAnimation 找不到相對應的  {0} 或 {1} 屬性",
    "Animation_NoPropertyFound": "Sys.Extended.UI.Animation.createAnimation 找不到相對應的 {0} 屬性",
    "Animation_TargetNotFound": "Sys.Extended.UI.Animation.Animation.set_animationTarget 需要一個 Sys.UI.DomElement 或 Sys.UI.Control 類別的控制項  ID。找不到相對應的  {0} 之項目或控制項",
    "Animation_UknownAnimationName": "Sys.Extended.UI.Animation.createAnimation 找不到名稱為 {0} 的動畫",
    "Calendar_Today": "今天:  {0}",
    "CascadingDropDown_MethodError": "[方法錯誤 {0}]",
    "CascadingDropDown_MethodTimeout": "[方法逾時]",
    "CascadingDropDown_NoParentElement": "無法找到父項目 {0}",
    "CollapsiblePanel_NoControlID": "無法找到項目 {0}",
    "Common_DateTime_InvalidFormat": "格式無效",
    "Common_DateTime_InvalidTimeSpan": "{0} 的 TimeSpan 格式無效",
    "Common_InvalidBorderWidthUnit": "單位類型 {0} 對 parseBorderWidth 而言無效",
    "Common_InvalidPaddingUnit": "單位類型 {0} 對 parsePadding 而言無效",
    "Common_UnitHasNoDigits": "沒有數字",
    "DynamicPopulate_WebServiceError": "無法呼叫 Web 服務：{0}",
    "DynamicPopulate_WebServiceTimeout": "呼叫 Web 服務逾時",
    "ExtenderBase_CannotSetClientStateField": "只能在初始化之前設定 clientStateField",
    "ExtenderBase_ControlNotRegisteredForCallbacks": "這個控制項尚未註冊，無法提供回呼",
    "ExtenderBase_InvalidClientStateType": "saveClientState 必須傳回 String 型別的值",
    "ExtenderBase_PageNotRegisteredForCallbacks": "這個頁面尚未註冊，無法提供回呼",
    "ListSearch_DefaultPrompt": "請鍵入以便搜尋",
    "PasswordStrength_DefaultStrengthDescriptions": "沒有;很弱;弱;差;差強人意;尚可;普通;好;很好;非常好;臻於完美！",
    "PasswordStrength_GetHelpRequirements": "取得密碼複雜性的要求說明",
    "PasswordStrength_InvalidStrengthDescriptions": "所指定的密碼複雜性文字內容個數無效",
    "PasswordStrength_InvalidStrengthDescriptionStyles": "密碼複雜性文字說明的樣式表，必須符合文字內容之個數",
    "PasswordStrength_InvalidWeightingRatios": "密碼複雜性的權重比例必須有 4 種",
    "PasswordStrength_RemainingCharacters": "還需要 {0} 個字元",
    "PasswordStrength_RemainingMixedCase": "大小寫混合",
    "PasswordStrength_RemainingNumbers": "還需要 {0} 個數字",
    "PasswordStrength_RemainingSymbols": "還需要 {0} 個符號",
    "PasswordStrength_Satisfied": "密碼複雜性已經足夠",
    "PasswordStrength_StrengthPrompt": "複雜性：",
    "PopupControl_NoDefaultProperty": "類型 {1} 的 控制項 {0} 不支援預設屬性",
    "PopupExtender_NoParentElement": "無法找到父項目 {0}",
    "Rating_CallbackError": "發生未處理的例外狀況：\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_CallbackError": "無法重新排列，請參考下面的說明：\\r\\n\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_NoChild": "無法找到 ID 為 {0} 的子清單",
    "ResizableControlBehavior_CannotChangeProperty": "不支援對 {0} 的變更",
    "ResizableControlBehavior_InvalidHandler": "{0} 處理常式不是函式、函式名稱、或是函式文字",
    "Shared_BrowserSecurityPreventsPaste": "您的瀏覽器安全性設定，不允許執行自動貼上的操作。請改用鍵盤快速鍵 Ctrl + V。",
    "Slider_NoSizeProvided": "請在 Slider 的 CSS Class 中，設定高度與寬度屬性的有效值",
    "Tabs_ActiveTabArgumentOutOfRange": "參數不是索引標籤 (Tab) 集合的成員",
    "Tabs_OwnerExpected": "於初始化之前，必須設定擁有者",
    "Tabs_PropertySetAfterInitialization": "於初始化之後，無法變更 {0}",
    "Tabs_PropertySetBeforeInitialization": "於初始化之前，無法變更 {0}",
    "ValidatorCallout_DefaultErrorMessage": "這個控制項無效"
};
