Sys.Extended.UI.Localization["zh-CHS"] = {
    "AlwaysVisible_ElementRequired": "必须为 Sys.Extended.UI.AlwaysVisibleControlBehavior 指定一个元素",
    "Animation_CannotNestSequence": "Sys.Extended.UI.Animation.ParallelAnimation 不能内含 Sys.Extended.UI.Animation.SequenceAnimation",
    "Animation_ChildrenNotAllowed": "Sys.Extended.UI.Animation.createAnimation 无法加入一个不是派生自 Sys.Extended.UI.Animation.ParentAnimation 且类型为 {0} 的子动画",
    "Animation_InvalidBaseType": "Sys.Extended.UI.Animation.registerAnimation 只能注册那些继承自 Sys.Extended.UI.Animation.Animation 的类型",
    "Animation_InvalidColor": "标记名称 Color 必须是 7 个字符的 16 进位字符串（例如：#246ACF），不能是 {0}",
    "Animation_MissingAnimationName": "Sys.Extended.UI.Animation.createAnimation 必须持有一个 AnimationName 属性的对象",
    "Animation_NoDynamicPropertyFound": "Sys.Extended.UI.Animation.createAnimation 找不到相对应的  {0} 或 {1} 属性",
    "Animation_NoPropertyFound": "Sys.Extended.UI.Animation.createAnimation 找不到相对应的 {0} 属性",
    "Animation_TargetNotFound": "Sys.Extended.UI.Animation.Animation.set_animationTarget 需要一个 Sys.UI.DomElement 或 Sys.UI.Control 类的控件  ID。找不到相对应的  {0} 之元素或控件",
    "Animation_UknownAnimationName": "Sys.Extended.UI.Animation.createAnimation 找不到名称为 {0} 的动画",
    "Calendar_Today": "今天:  {0}",
    "CascadingDropDown_MethodError": "[方法错误 {0}]",
    "CascadingDropDown_MethodTimeout": "[方法逾时]",
    "CascadingDropDown_NoParentElement": "无法找到父元素 {0}",
    "CollapsiblePanel_NoControlID": "无法找到元素 {0}",
    "Common_DateTime_InvalidFormat": "格式无效",
    "Common_DateTime_InvalidTimeSpan": "{0} 的 TimeSpan 格式无效",
    "Common_InvalidBorderWidthUnit": "单位类型 {0} 对 parseBorderWidth 而言无效",
    "Common_InvalidPaddingUnit": "单位类型 {0} 对 parsePadding 而言无效",
    "Common_UnitHasNoDigits": "没有数字",
    "DynamicPopulate_WebServiceError": "无法调用 Web 服务：{0}",
    "DynamicPopulate_WebServiceTimeout": "调用 Web 服务超时",
    "ExtenderBase_CannotSetClientStateField": "只能在初始化之前设定 clientStateField",
    "ExtenderBase_ControlNotRegisteredForCallbacks": "这个控件尚未注册，无法提供回调",
    "ExtenderBase_InvalidClientStateType": "saveClientState 必须返回 String 类型的值",
    "ExtenderBase_PageNotRegisteredForCallbacks": "这个页面尚未注册，无法提供回调",
    "ListSearch_DefaultPrompt": "请键入以便搜寻",
    "PasswordStrength_DefaultStrengthDescriptions": "没有;很弱;弱;差;差强人意;尚可;普通;好;很好;非常好;臻于完美！",
    "PasswordStrength_GetHelpRequirements": "取得密码强度的要求说明",
    "PasswordStrength_InvalidStrengthDescriptions": "所指定的密码强度文字内容个数无效",
    "PasswordStrength_InvalidStrengthDescriptionStyles": "密码强度文字说明的样式表，必须符合文字内容之个数",
    "PasswordStrength_InvalidWeightingRatios": "密码强度的权重比例必须有 4 种",
    "PasswordStrength_RemainingCharacters": "还需要 {0} 个字符",
    "PasswordStrength_RemainingMixedCase": "大小写混合",
    "PasswordStrength_RemainingNumbers": "还需要 {0} 个数字",
    "PasswordStrength_RemainingSymbols": "还需要 {0} 个符号",
    "PasswordStrength_Satisfied": "密码强度已经足够",
    "PasswordStrength_StrengthPrompt": "强度：",
    "PopupControl_NoDefaultProperty": "类型 {1} 的 控件 {0} 不支持预设属性",
    "PopupExtender_NoParentElement": "无法找到父元素 {0}",
    "Rating_CallbackError": "发生未处理的异常状况：\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_CallbackError": "无法重新排列，请参考下面的说明：\\r\\n\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_NoChild": "无法找到 ID 为 {0} 的子清单",
    "ResizableControlBehavior_CannotChangeProperty": "不支持对 {0} 的变更",
    "ResizableControlBehavior_InvalidHandler": "{0} 处理例程不是函数、函数名称、或是函数文字",
    "Shared_BrowserSecurityPreventsPaste": "您的浏览器安全性设定，不允许执行自动粘贴的操作。请改用键盘快捷键 Ctrl + V。",
    "Slider_NoSizeProvided": "请在 Slider 的 CSS Class 中，设定高度与宽度属性的有效值",
    "Tabs_ActiveTabArgumentOutOfRange": "参数不是索引标签 (Tab) 集合的成员",
    "Tabs_OwnerExpected": "于初始化之前，必须设定拥有者",
    "Tabs_PropertySetAfterInitialization": "于初始化之后，无法变更 {0}",
    "Tabs_PropertySetBeforeInitialization": "于初始化之前，无法变更 {0}",
    "ValidatorCallout_DefaultErrorMessage": "这个控件无效"
};
