Sys.Extended.UI.Localization["pl"] = {
    "Calendar_Today": "Dzisiaj: {0}",
    "AjaxFileUpload_DropFiles": "Przeciągnij tutaj pliki",
    "AjaxFileUpload_AllFilesUploaded": "Wszystkie pliki przesłane.",
    "AjaxFileUpload_SelectFile": "Wybierz plik",
    "AjaxFileUpload_Remove": "Usuń",
    "AjaxFileUpload_Upload": "Prześlij",
    "AjaxFileUpload_Cancel": "Anuluj",
    "AjaxFileUpload_FileList": "Lista przesłanych plików:",
    "AjaxFileUpload_SelectFileToUpload": "Wybierz plik(i) do przesłania.",
    "AjaxFileUpload_Pending": "oczekuje",
    "AjaxFileUpload_FileInQueue": "Plików w kolejce: {0}",
    "AjaxFileUpload_UploadingFileInQueue": "Przesyłam {0} z {1} plików",
    "AjaxFileUpload_UploadingHtml5File": "Przesyłanie pliku: {0} z {1} bajtów.",
    "AjaxFileUpload_UploadingInputFile": "Przesyłanie pliku: {0}.",
    "AjaxFileUpload_UploadError": "W trakcie przesyłania pliku wystąpił błąd.",
    "AjaxFileUpload_DefaultError": "Błąd przesyłania pliku.",
    "AjaxFileUpload_UploadedPercentage": "przesłano {0} %",
    "AjaxFileUpload_Uploading": "Przesyłam",
    "AjaxFileUpload_Uploaded": "Przesłano",
    "AjaxFileUpload_Cancelling": "Anulowanie...",
    "AjaxFileUpload_CancellingUpload": "Anulowanie przesyłania...",
    "AjaxFileUpload_UploadCanceled": "Przesyłanie pliku anulowane.",
    "AjaxFileUpload_Canceled": "anulowano",
    "AjaxFileUpload_error": "błąd",
    "AjaxFileUpload_MaxNumberOfFilesExceeded": "Wybrano zbyt dużo plików do przesyłania",
    "AjaxFileUpload_WrongFileType": "Nie można dodać pliku \u0027{0}\u0027 do listy przesyłania. Pliki z roszerzeniem \u0027{1}\u0027 są niedozwolone.",
    "AjaxFileUpload_TooLargeFile": "Plik \u0027{0}\u0027 przekracza maksymalny rozmiar {1} Kbajtów."
};
