Sys.Extended.UI.Localization["fr"] = {
    "Calendar_Today": "Aujourd\u0027hui : {0}",
    "AjaxFileUpload_DropFiles": "Glisser les fichiers ici",
    "AjaxFileUpload_AllFilesUploaded": "Tous les files ont été envoyés.",
    "AjaxFileUpload_SelectFile": "Sélectionner un fichier",
    "AjaxFileUpload_Remove": "Supprimer",
    "AjaxFileUpload_Upload": "Envoi",
    "AjaxFileUpload_Cancel": "Annuler",
    "AjaxFileUpload_FileList": "Liste des fichiers envoyés :",
    "AjaxFileUpload_SelectFileToUpload": "Veuiller sélectionner le(s) fichier(s) à envoyer.",
    "AjaxFileUpload_Pending": "en attente",
    "AjaxFileUpload_FileInQueue": "{0} fichier(s) dans la file d\u0027attente.",
    "AjaxFileUpload_UploadingHtml5File": "Envoi de fichier : {0} sur un total de {1} octets.",
    "AjaxFileUpload_UploadingInputFile": "Envoi du fichier : {0}.",
    "AjaxFileUpload_UploadError": "Une erreur est survenu lors l\u0027envoi de fichier.",
    "AjaxFileUpload_DefaultError": "Error lors de l\u0027envoi du fichier.",
    "AjaxFileUpload_UploadedPercentage": "{0} % envoyé",
    "AjaxFileUpload_Uploading": "Envoi",
    "AjaxFileUpload_Uploaded": "Envoyé",
    "AjaxFileUpload_Cancelling": "Annulation en cours",
    "AjaxFileUpload_CancellingUpload": "Annulation de l\u0027envoi...",
    "AjaxFileUpload_UploadCanceled": "Envoi de fichier annulé.",
    "AjaxFileUpload_Canceled": "annulé",
    "AjaxFileUpload_error": "erreur",
    "AjaxFileUpload_MaxNumberOfFilesExceeded": "Maximum number of files exceeded",
    "AjaxFileUpload_WrongFileType": "Can\u0027t add file \u0027{0}\u0027 to upload list. File with type \u0027{1}\u0027 is not allowed"
};
