Sys.Extended.UI.Localization["tr"] = {
    "AlwaysVisible_ElementRequired": "Sys.Extended.UI.AlwaysVisibleControlBehavior element içermek zorundadır",
    "Animation_CannotNestSequence": "Sys.Extended.UI.Animation.SequenceAnimation Sys.Extended.UI.Animation.ParallelAnimation içinde yer alamaz",
    "Animation_ChildrenNotAllowed": "Sys.Extended.UI.Animation.createAnimation Sys.Extended.UI.Animation.ParentAnimation dan türetilmeyen alt animasyonları \"{0}\" tipine ekleyemez",
    "Animation_InvalidBaseType": "Sys.Extended.UI.Animation.registerAnimation sadece Sys.Extended.UI.Animation.Animation dan türetilmiş tipleri kayıt edebilir",
    "Animation_InvalidColor": "Renk tanımı \"{0}\" şeklinde değil 7-karakter 16\u0027lık sayı düzeninde belirtilmelidir (örneğin #246ACF)",
    "Animation_MissingAnimationName": "Sys.Extended.UI.Animation.createAnimation AnimationName özelliği olan bir objeye ihtiyaç duyar",
    "Animation_NoDynamicPropertyFound": "Sys.Extended.UI.Animation.createAnimation \"{0}\" veya \"{1}\" ile uygun bir özellik bulamadı",
    "Animation_NoPropertyFound": "Sys.Extended.UI.Animation.createAnimation \"{0}\" ile uygun bir özellik bulamadı",
    "Animation_TargetNotFound": "\"{0}\" ile uygun element veya kontrol bulunamadı. Sys.Extended.UI.Animation.Animation.set_animationTarget Sys.UI.DomElement veya Sys.UI.Control ID ye ihtiyaç duyar.",
    "Animation_UknownAnimationName": "Sys.Extended.UI.Animation.createAnimation \"{0}\" isminde bir Animasyon bulamadı",
    "Calendar_Today": "Bugün: {0}",
    "CascadingDropDown_MethodError": "[Metot hatası {0}]",
    "CascadingDropDown_MethodTimeout": "[Metot zaman aşımı]",
    "CascadingDropDown_NoParentElement": "\"{0}\" kök elementi bulunamadı",
    "CollapsiblePanel_NoControlID": "\"{0}\" elementi bulunamadı",
    "Common_DateTime_InvalidFormat": "Yanlış format",
    "Common_DateTime_InvalidTimeSpan": "\"{0}\" geçerli bir TimeSpan formatı değil",
    "Common_InvalidBorderWidthUnit": "\"{0}\" birim tipi parseBorderWidth için geçersiz",
    "Common_InvalidPaddingUnit": "\"{0}\" birim tipi parsePadding için geçersiz",
    "Common_UnitHasNoDigits": "Rakam yok",
    "DynamicPopulate_WebServiceError": "Web Servis çağrısı başarısız oldu: {0}",
    "DynamicPopulate_WebServiceTimeout": "Web Servis çağrısı zaman aşımına uğradı",
    "ExtenderBase_CannotSetClientStateField": "clientStateField sadece başlangıç noktasından önce ayarlanabilir",
    "ExtenderBase_ControlNotRegisteredForCallbacks": "Bu kontrol geri arama işlemleri için kaydedilmedi",
    "ExtenderBase_InvalidClientStateType": "saveClientState String tipinde bir değer döndürmelidir",
    "ExtenderBase_PageNotRegisteredForCallbacks": "Bu sayfa geri arama işlemleri için kaydedilmedi",
    "ListSearch_DefaultPrompt": "Arama için yazın",
    "PasswordStrength_DefaultStrengthDescriptions": "Kabul Edilemez;Çok Zayıf;Zayıf;Biraz Zayıf;Vasat;Kabul Edilebilir;Ortalama;İyi;Güçlü;Mükemmel;Kırılamaz!",
    "PasswordStrength_GetHelpRequirements": "Şifre gereksinimleri hakkında yardım al",
    "PasswordStrength_InvalidStrengthDescriptions": "Yanlış sayıda şifre yetkinliği tanımı belirlendi",
    "PasswordStrength_InvalidStrengthDescriptionStyles": "Şifre yetkinliği tanımlama stil sınıfları yazım tariflerinin sayısına eşit olmalıdır",
    "PasswordStrength_InvalidWeightingRatios": "Şifre yetkinliği oranı 4 elemente sahip olmalıdır",
    "PasswordStrength_RemainingCharacters": "{0} harf daha",
    "PasswordStrength_RemainingMixedCase": "Karmaşık tipte harf",
    "PasswordStrength_RemainingNumbers": "{0} sayı daha",
    "PasswordStrength_RemainingSymbols": "{0} sembol daha",
    "PasswordStrength_Satisfied": "Şifre yetkinliği sağlandı",
    "PasswordStrength_StrengthPrompt": "Şifre yetkinliği:",
    "PopupControl_NoDefaultProperty": "\"{1}\" tipindeki \"{0}\" kontrolü için varsayılan bir özellik belirlenmedi",
    "PopupExtender_NoParentElement": "\"{0}\" kök elementi bulunamadı",
    "Rating_CallbackError": "İşlenemez bir hata oluştu:\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_CallbackError": "Yeniden düzenleme başarısız oldu, detayı aşağıda.\\r\\n\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_NoChild": "Listede id \"{0}\" olan bir alt birim bulunamadı",
    "ResizableControlBehavior_CannotChangeProperty": "{0} üstündeki değişiklikleri desteklenmemektedir",
    "ResizableControlBehavior_InvalidHandler": "{0} işleyicisi fonksiyon, fonksiyon ismi veya fonksiyon metni değil",
    "Shared_BrowserSecurityPreventsPaste": "Tarayıcınızın güvenlik ayarları otomatik yapıştırma işlemine izin vermemektedir. Lütfen Ctrl+V klavye kısayolunu kullanın.",
    "Slider_NoSizeProvided": "Lütfen kaydırıcının (slider) CSS sınıflarında genişlik ve yükseklik için geçerli değerler kullanın",
    "Tabs_ActiveTabArgumentOutOfRange": "Argüman sekme koleksiyonunun bir üyesi değil",
    "Tabs_OwnerExpected": "Başlangıç noktasına gelmeden önce sahip belirlenmelidir",
    "Tabs_PropertySetAfterInitialization": "Başlangıç noktası geçildikten sonra {0} değiştirilemez",
    "Tabs_PropertySetBeforeInitialization": "Başlangıç noktasına varılmadan önce {0} değiştirilemez",
    "ValidatorCallout_DefaultErrorMessage": "Bu kontrol geçersiz"
};
