namespace AjaxControlToolkit {
    internal static class Constants {
        internal const string
            JsPostfix = ".js",
            DebugJsPostfix = ".debug" + JsPostfix,

            CssPostfix = ".css",
            MinCssPostfix = ".min" + CssPostfix,

            IconPostfix = ".ico",

            ContentVirtualPath = "~/Content/AjaxControlToolkit/",
            StylesVirtualPath = ContentVirtualPath + "Styles/",
            ImagesVirtualPath = ContentVirtualPath + "Images/",
            ScriptsVirtualPath = "~/Scripts/AjaxControlToolkit/",
            ScriptsDebugVirtualPath = ScriptsVirtualPath + "Debug/",
            ScriptsReleaseVirtualPath = ScriptsVirtualPath + "Release/",

            ImageResourcePrefix = "AjaxControlToolkit.Images.",
            StyleResourcePrefix = "AjaxControlToolkit.Styles.",

            BackgroundStylesName = "Backgrounds",
            BaseScriptName = "BaseScripts",
            CommonScriptName = "Common",
            CompatDragDropScriptName = "Compat.DragDrop",
            CompatTimerScriptName = "Compat.Timer",
            DateTimeScriptName = "Common.DateTime",
            LocalizationScriptName = "Localization.Resources",
            ThreadingScriptName = "Common.Threading",

            AccordionName = "Accordion",
            AlwaysVisibleControlName = "AlwaysVisibleControl",
            AnimationName = "Animation",
            AnimationScriptsName = "AnimationScripts",
            AutoCompleteName = "AutoComplete",
            CalendarName = "Calendar",
            CascadingDropDownName = "CascadingDropDown",
            CollapsiblePanelName = "CollapsiblePanel",
            DynamicPopulateName = "DynamicPopulate",
            DraggableListItemName = "DraggableListItem",
            DragPanelName = "DragPanel",
            DropDownName = "DropDown",
            DropShadowName = "DropShadow",
            DropWatcherName = "DropWatcher",
            FilteredTextBoxName = "FilteredTextBox",
            HoverMenuName = "HoverMenu",
            HoverName = "Hover",
            MaskedEditName = "MaskedEdit",
            MaskedEditValidatorName = "MaskedEditValidator",
            MutuallyExclusiveCheckBoxName = "MutuallyExclusiveCheckBox",
            NoBotName = "NoBot",
            NumericUpDownName = "NumericUpDown",
            PagingBulletedListName = "PagingBulletedList",
            PasswordStrengthName = "PasswordStrength",
            PopupName = "Popup",
            RatingName = "Rating",
            ReorderListName = "ReorderList",
            ResizableControlName = "ResizableControl",
            RoundedCornersName = "RoundedCorners",
            SliderName = "Slider",
            SlideShowName = "SlideShow",
            TextBoxWatermarkName = "TextBoxWatermark",
            ToggleButtonName = "ToggleButton",
            UpdatePanelAnimationName = "UpdatePanelAnimation",
            ValidatorCalloutName = "ValidatorCallout",

            CalendarArrowLeftImage = CalendarName + "Arrow-Left.gif",
            CalendarArrowRightImage = CalendarName + "Arrow-Right.gif",
            DropDownDropArrowImage = DropDownName + "Drop-Arrow.gif",
            SliderVerticalRailImage = SliderName + "Rail-V.gif",
            SliderHorizontalRailImage = SliderName + "Rail-H.gif",
            SliderVerticalHandleImage = SliderName + "Handle-V.gif",
            SliderHorizontalHandleImage = SliderName + "Handle-H.gif",
            ValidatorCalloutAlertLargeImage = ValidatorCalloutName + "Alert-Large.gif",
            ValidatorCalloutAlertSmallImage = ValidatorCalloutName + "Alert-Small.gif",
            ValidatorCalloutCloseImage = ValidatorCalloutName + "Close.gif";
    }
}
